In [1]:
# https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch
# https://inmoonlight.github.io/2021/03/03/PyTorch-view-transpose-reshape/
import torch

In [46]:
# 3차원에서 실험해볼때 예시
t = torch.tensor(
    [
        [[0, 1], [2, 3], [4, 5]],
        [[6, 7], [8, 9], [10, 11]],
        [[12, 13], [14, 15], [16, 17]],
        [[18, 19], [20, 21], [22, 23]],
    ]
)  # (4, 3, 2)
print(t)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]])


In [10]:
# view는 차원을 뒤틀어서 눕히는 것이 아니고, 그냥 연속된 차원 맞추기 일 뿐이다.
tv = t.view(4, 2, 3)
print(tv)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]])


In [12]:
tv.is_contiguous()

True

In [16]:
print(t.flatten())
print(tv.flatten())
print(t.flatten() == tv.flatten())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True])


In [22]:
# 저장 포인터까지 동일하여, shallow copy 효과가 날 것이다.
t.untyped_storage().data_ptr() == tv.untyped_storage().data_ptr()

True

In [24]:
# transpose는 배열 자체를 눕히고 돌린다 (회전?)
tt = t.transpose(2, 1)
print(tt)

tensor([[[ 0,  2,  4],
         [ 1,  3,  5]],

        [[ 6,  8, 10],
         [ 7,  9, 11]],

        [[12, 14, 16],
         [13, 15, 17]],

        [[18, 20, 22],
         [19, 21, 23]]])


In [42]:
# 2차원으로 예시 해보기
test = torch.arange(8).reshape(4,2)

In [43]:
print(test)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])


In [45]:
print("transpose: ", test.transpose(0,1))
print("reshape: ", test.reshape(2,-1))
print("view: ", test.view(2,-1))

transpose:  tensor([[0, 2, 4, 6],
        [1, 3, 5, 7]])
reshape:  tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
view:  tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


In [41]:
test.reshape(4,-1).is_contiguous()

True